on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use my Action
      uses: ./ # Uses an action in the root directory
      with:
        template-file: './md/template.json'
        replacement-directory: './md'
        check-modified-files-only: 'no'
        base-branch: 'master'
    - name: Commit and push if changed
      run: |
        git diff
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a || echo "No changes to commit"
        git push
